### ISSUE TITLE
Feedback function in the "About" popup

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStatsWebserviceDocumentation#66]
Doesn't seem to submit a new issue to GitHub. Seems to just close the popup!

**Comment by marsmith** [comment]
hilarious

On Thu, Sep 17, 2015 at 3:40 PM, Hans Vraga notifications@github.com
wrote:

> Doesn't seem to submit a new issue to GitHub. Seems to just close the
> popup!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-WiM/StreamStatsWebserviceDocumentation/issues/66
> .

## 

Martyn Smith
Cartographer
_marsmith@usgs.gov_ marsmith@usgs.gov
518.285.5618

**Comment by HansVraga** [comment]
I'm a funny guy.
